/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.jec.iu;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;

/**
 *
 * @author jescobar
 */
public class LienzoImagen2D extends Lienzo2D {

    private BufferedImage img;
    /**
     * Creates new form LienzoImagen2D
     */
    public LienzoImagen2D() {
        initComponents();
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        if(img!=null)
            g.drawImage(img,0,0,this);
    }

    public BufferedImage getImage(boolean drawVector) {
        if(drawVector){
            BufferedImage imgOut = new BufferedImage(img.getWidth(),img.getHeight(),img.getType());
            this.paint(imgOut.createGraphics());
            return imgOut;
        }
        else
            return img;
    }

    public void setImage(BufferedImage image) {
        this.img = image;
        if(img!=null) {
            setPreferredSize(new Dimension(img.getWidth(),img.getHeight()));
        }
    }
    
    private void clear(){
        Rectangle2D.Float r = new Rectangle2D.Float(0,0,300,300);
        this.setColor(Color.WHITE);
        this.setFill(true);
        this.getvShape().add(r);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
