/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.jec.practicafinal;

import sm.jec.iu.LienzoImagen2D;

/**
 *
 * @author jescobar
 */
public class VentanaInternaImagen extends VentanaInterna {//javax.swing.JInternalFrame {
    private final VentanaPrincipal parent;
    /**
     * Creates new form VentanaInternaImagen
     */
    public VentanaInternaImagen(VentanaPrincipal parent) {
        super();
        this.parent = parent;
        initComponents();
        this.setSize(300, 300);
        this.tipo = "imagen";
    }
    public LienzoImagen2D getLienzo() {
        return lienzoImagen2D1;
    }

    public void setLienzo(LienzoImagen2D lienzoImagen2D1) {
        this.lienzoImagen2D1 = lienzoImagen2D1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzoImagen2D1 = new sm.jec.iu.LienzoImagen2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout lienzoImagen2D1Layout = new javax.swing.GroupLayout(lienzoImagen2D1);
        lienzoImagen2D1.setLayout(lienzoImagen2D1Layout);
        lienzoImagen2D1Layout.setHorizontalGroup(
            lienzoImagen2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        lienzoImagen2D1Layout.setVerticalGroup(
            lienzoImagen2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzoImagen2D1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.jec.iu.LienzoImagen2D lienzoImagen2D1;
    // End of variables declaration//GEN-END:variables
}
